runtime: nodejs14

env_variables:
  SHOPIFY_API_KEY: "420ebcf66e379eadada52ddd5fa2d8fd"
  SHOPIFY_API_SECRET: "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"
  SHOP: "lycklig-mug-store.myshopify.com"
  SCOPES: "write_products,write_customers,write_draft_orders,read_orders,write_discounts,write_script_tags,unauthenticated_write_checkouts,unauthenticated_read_product_listings,unauthenticated_read_product_tags"
  HOST: "https://mandatum-app.uc.r.appspot.com"