runtime: nodejs14

instance_class: F1

automatic_scaling:
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  target_cpu_utilization: 0.8
  max_concurrent_requests: 80

env_variables:
  SHOPIFY_API_KEY: "420ebcf66e379eadada52ddd5fa2d8fd"
  SHOPIFY_API_SECRET: "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"
  SHOP: "lycklig-mug-store.myshopify.com"
  SCOPES: "write_products,write_customers,write_draft_orders,read_orders,write_discounts,write_script_tags,unauthenticated_write_checkouts,unauthenticated_read_product_listings,unauthenticated_read_product_tags"
  HOST: "https://mandatum-app.uc.r.appspot.com"
  SGKEY: "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"